# Regression Algorithms

In [59]:
import numpy as np
import scipy

# used for testing
from sklearn.linear_model import LinearRegression, Ridge, LogisticRegression

## Linear Regression (OLS)

The ordinary least square is a type of linear regression that minimizes the sum of squares between the dependent variable and the predicted value. The normal equation finds the value of parameters that minimizes the sum of squares: $b = (X^TX)^{-1}X^Ty$. In the equation, $y$ is the vector of the predicted value, $X$ is the dependent variables, and $b$ is the parameters that minizimes the sum of squares.

In [28]:
class ordinaryLeastSquare():
    """
    """
    
    def __init__(self, fit_intercept=True):
        """
        """
        self.fit_intercept = fit_intercept
        
    def fit(self, X, y):
        """
        """
        X = np.c_[np.ones((len(X), 1)), X] # add column of 1 to the beginning
        X_transpose = X.T # transpose matrix
        ols = np.linalg.inv(X_transpose.dot(X)).dot(X_transpose).dot(y)
        return ols
    
    def fit_predict(self, X, y):
        """
        """
        param = self.fit(X, y)
        dependent = np.c_[np.ones((len(X), 1)), X] # add column of 1 to the beginning
        predicted_value = dependent.dot(param)
        return predicted_value

In [49]:
############ Linear Regression ############
np.random.seed(42)
X = 2 * np.random.rand(100, 1)
y = 4 + 3 * X + np.random.rand(100, 1)

param = ordinaryLeastSquare().fit(X, y)
predicted = ordinaryLeastSquare().fit_predict(X, y)

param_sk = LinearRegression().fit(X, y)
predicted_sk = param_sk.predict(X)

assert np.round(param[0][0], 5) == np.round(param_sk.intercept_[0], 5)
assert np.round(param[1][0], 5) == np.round(param_sk.coef_[0][0], 5)
assert (predicted == predicted_sk).all

############ Multiple Linear Regression ############

## Polynomial Regression

## Logistic Regression

Logistic regression is a binary classifier and is commonly used to estimate the probability that an instance belongs to a particular class. If the estimated probability is greater than 50% then the model predicts that the instance belongs to that class, and otherwise it predicts that is not. The logistic regression can be represented by the following equation:

$\sigma(t) = \frac{1}{1 + e^{X^T\theta}}$ where $X$ is the dependent variable and $\theta$ is the parameters.

- https://machinelearningmastery.com/implement-logistic-regression-stochastic-gradient-descent-scratch-python/
- https://medium.com/@martinpella/logistic-regression-from-scratch-in-python-124c5636b8ac

In [146]:
class LogisticRegressionHC():
    """
    """
    
    def __init__(self, l_rate = 0.1, n_epoch = 100, add_intercept=True):
        self.l_rate = l_rate
        self.n_epoch = n_epoch
        self.add_intercept = add_intercept
            
    def fit(self, X, y):
        """
        Fit Logistic Regression model
        """
        if self.add_intercept:
            X = np.c_[np.ones((len(X), 1)), X] # add row of 1
        
        # add weight initialization
        self.theta = np.zeros(X.shape[1])
        
        for epoch in range(self.n_epoch):
            linear_combination = np.dot(X, self.theta)
            y_hat = 1.0 / (1.0 + np.exp(-linear_combination))  # sigmoid function
            cfpd = np.dot(X.T, y_hat - y) / y.size  # cost function partial derivative
            self.theta -= self.l_rate * cfpd
            
        return self
            
    def predict_proba(self, X):
        """
        """
        if self.add_intercept:
            X = np.c_[np.ones((len(X), 1)), X]
            
        prob1 = 1.0 / (1.0 + np.exp( np.dot(X, self.theta) ))
        prob2 = 1 - prob1
        
        return np.c_[prob1, prob2]
    
    def predict(self, X, threshold = 0.5):
        """
        """
        pass

In [147]:
from sklearn import datasets
iris = datasets.load_iris()

X = iris["data"][:, 3:]
y = (iris["target"] == 2).astype(np.int)
log_reg = LogisticRegressionHC(n_epoch=300, l_rate = 0.01).fit(X, y)
print(log_reg.predict_proba(X))

log_sk = LogisticRegression(fit_intercept=True).fit(X, y)
print(log_sk.coef_)
print(log_sk.intercept_)

[[0.59624046 0.40375954]
 [0.59624046 0.40375954]
 [0.59624046 0.40375954]
 [0.59624046 0.40375954]
 [0.59624046 0.40375954]
 [0.58427623 0.41572377]
 [0.5902717  0.4097283 ]
 [0.59624046 0.40375954]
 [0.59624046 0.40375954]
 [0.60218086 0.39781914]
 [0.59624046 0.40375954]
 [0.59624046 0.40375954]
 [0.60218086 0.39781914]
 [0.60218086 0.39781914]
 [0.59624046 0.40375954]
 [0.58427623 0.41572377]
 [0.58427623 0.41572377]
 [0.5902717  0.4097283 ]
 [0.5902717  0.4097283 ]
 [0.5902717  0.4097283 ]
 [0.59624046 0.40375954]
 [0.58427623 0.41572377]
 [0.59624046 0.40375954]
 [0.57825571 0.42174429]
 [0.59624046 0.40375954]
 [0.59624046 0.40375954]
 [0.58427623 0.41572377]
 [0.59624046 0.40375954]
 [0.59624046 0.40375954]
 [0.59624046 0.40375954]
 [0.59624046 0.40375954]
 [0.58427623 0.41572377]
 [0.60218086 0.39781914]
 [0.59624046 0.40375954]
 [0.59624046 0.40375954]
 [0.59624046 0.40375954]
 [0.59624046 0.40375954]
 [0.60218086 0.39781914]
 [0.59624046 0.40375954]
 [0.59624046 0.40375954]


In [54]:
np.array([0.2, 0.0])[:-1]

array([0.2])

## Regularized Linear Regression

### Ridge Regression

The Ridge Regression is a regularized version of linear regression in which a regularization term $\alpha\sum\limits_{i=1}^n\theta_i^2$ is added to the cost function. The equation for Ridge Regression is $\theta = (X^TX + \alpha A)^{-1}X^T y$ where $X$ is the dependent variable, $y$ is the independent variable, $\alpha$ is the regularization strength, and $A$ is the identity matrix.

In [83]:
class RidgeRegression():
    """
    """
    
    def __init__(self, alpha=1.0, fit_intercept=True):
        self.alpha = alpha
        self.fit_intercept = fit_intercept
        
    def fit(self, X, y):
        """
        Fit Ridge Regression model
        
        """
        X = np.c_[np.ones((len(X), 1)), X] # add column of 1 to the beginning
        identity_matrix = np.identity(len(X[0]))
        X_transpose = X.T
        ridge_param = scipy.linalg.inv( X_transpose.dot(X) + self.alpha*(identity_matrix) ).dot(X_transpose).dot(y)
        return ridge_param
    
    def predict(self, X, y):
        """
        
        """
        param = self.fit(X, y)
        dependent_var = np.c_[np.ones((len(X), 1)), X] # add column of 1 to the beginning
        predicted_value = dependent_var.dot(param)
        return predicted_value

In [84]:
np.random.seed(42)
X = 2 * np.random.rand(100, 1)
y = 4 + 3 * X + np.random.rand(100, 1)

ridge = RidgeRegression().fit(X, y)
predict = RidgeRegression().predict(X, y)

ridge_sk = Ridge(solver="cholesky").fit(X, y)
predict_sk = ridge_sk.predict(X)

In [85]:
print(ridge)
print('\n')
print(ridge_sk.intercept_)
print(ridge_sk.coef_)

[[4.43816508]
 [3.01625437]]


[4.59142377]
[[2.90047227]]


### Lasso Regression

https://towardsdatascience.com/ridge-and-lasso-regression-a-complete-guide-with-python-scikit-learn-e20e34bcbf0b

no closed form solution

### Elastic Net

## Gradient Descent

### Batch Gradient Descent

To implement Gradient Descent, we need to compute the gradient of the cost function with regard to each model parameter. We use the equation $\nabla_\theta MSE(\theta) = \frac{2}{m}X^T (X\theta - y)$ to find the gradient vector which contains all the partial derivatives of the cost function.

To determine the model parameter, we use the equation $\theta^{next step} = \theta - \eta\nabla_\theta MSE(\theta)$ where $\eta$ is the learning rate.

In [17]:
class BatchGradientDescent():
    """
    """
    def __init__(self, eta = 0.1, n_iterations = 1000):
        self.eta = eta
        self.n_iterations = n_iterations

    def fit(self, X, y):
        """
        Fit Batch Gradient Descent model
        """
        X = np.c_[np.ones((len(X), 1)), X]
        m = len(X)
        theta = np.random.rand(2,1)
        
        for iterations in range(self.n_iterations):
            gradient = 2/m * X.T.dot(X.dot(theta) - y)
            theta = theta - eta * gradient
        
        return theta
    
    def predict(self, X):
        pass

In [75]:
# Test
np.random.seed(42)
X = 2 * np.random.rand(100, 1)
y = 4 + 3 * X + np.random.rand(100, 1)

bgd = BatchGradientDescent().fit(X, y)
lr = LinearRegression().fit(X, y)

assert np.round(bgd[0][0], 5) == np.round(lr.intercept_[0], 5) # check intercept
assert np.round(bgd[1][0], 5) == np.round(lr.coef_[0][0], 5) # check coefficient
print("Slope:{}, Intercept:{}".format(bgd[1][0], bgd[0][0]))

Slope:2.9832341780601985, Intercept:4.513597656401026


### Stochastic Gradient Descent

Stochastic Gradient Descent picks a random instance in the training set at every set and computes the gradients based only on the single instance. Working on a single instance makes the algorithm run much faster.

Unlike Batch Gradient Descent, the cost function will bounce up and down which decreases only on average. Over time it will end up very close to the minimum but will continue to bounce. Therefore, the final parameter values are good, but not optimal. 

In [87]:
class StochasticGradientDescent():
    """
    """
    def __init__(self, t0, t1, n_epochs=50):
        self.n_epochs = n_epochs
        self.t0 = t0
        self.t1 = t1
        
    def learning_schedule(self, t):
        return self.t0 / (t + self.t1)
        
    def fit(self, X, y):
        # initialize values
        m = len(X)
        theta = np.random.randn(2, 1)
        X = np.c_[np.ones((len(X), 1)), X]
        
        for epoch in range(self.n_epochs):
            for i in range(m):
                random_index = np.random.randint(m)
                xi = X[random_index:random_index+1]
                yi = y[random_index:random_index+1]
                
                gradients = 2 * xi.T.dot(xi.dot(theta) - yi) # cost function
                eta = self.learning_schedule(epoch * m + i)  # make learning schedule smaller each iteration
                theta = theta - eta * gradients # gradient descend step
                
        return theta
                
    def predict(self, X):
        pass

In [88]:
np.random.seed(42)
X = 2 * np.random.rand(100, 1)
y = 4 + 3 * X + np.random.rand(100, 1)

sgd = StochasticGradientDescent(t0=5, t1=50, n_epochs=50).fit(X, y)
print("Slope:{}, Intercept:{}".format(sgd[1][0], sgd[0][0]))

Slope:2.985535560235501, Intercept:4.51950801515712


### Mini-Batch Gradient Descent

At each step, Mini-Batch Gradient Descent computes the gradients on small random sets of instances. 

In [69]:
class MiniBatchGradientDescent():
    """
    """
    def __init__(self, t0, t1, n_iterations = 50, minibatch_size = 20):
        self.t0 = t0
        self.t1 = t1
        self.n_iterations = n_iterations
        self.minibatch_size = minibatch_size
        
    def learning_schedule(self, t):
        return self.t0 / (t + self.t1)
        
    def fit(self, X, y):
        """
        """
        t = 0
        m = len(X)
        X = np.c_[np.ones((len(X), 1)), X]
        theta = np.random.randn(2, 1) # random initialization
        
        for epoch in range(n_iterations):
            # shuffle data
            shuffled_indices = np.random.permutation(m)
            X_shuffled = X[shuffled_indices]
            y_shuffled = y[shuffled_indices]
            
            for i in range(0, m, self.minibatch_size):
                t += 1 # make learning schedule smaller each iteration
                
                # get mini-natch
                xi = X_shuffled[i:i+self.minibatch_size]
                yi = y_shuffled[i:i+self.minibatch_size]
                gradients = (2/self.minibatch_size) * xi.T.dot(xi.dot(theta) - yi) # cost function
                eta = self.learning_schedule(t)
                theta = theta - eta * gradients # gradient descend step
                
        return theta
    
    def predict(self, X):
        """
        """
        pass

In [74]:
np.random.seed(42)
X = 2 * np.random.rand(100, 1)
y = 4 + 3 * X + np.random.rand(100, 1)

sgd = MiniBatchGradientDescent(t0=200, t1=1000).fit(X, y)
print("Slope:{}, Intercept:{}".format(sgd[1][0], sgd[0][0]))

Slope:2.983626806252817, Intercept:4.513988199056129
